<<<<<<< HEAD
baseurl: http://spa-js.github.io
=======
baseurl: ''
>>>>>>> gh-pages
name: Single Page Apps
description: 'Centralized recommendations, guidelines, and best practices for SPA (Single Page Apps)'
#GitHub Pages defaults
safe: true
lsi: false
pygments: true
